---
- hosts: all
  become: true
  tasks:
    - name: Installing Apache & PHP support for Ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install repository index
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Installing Apache & PHP support for Red-Hat
      yum:
        name:
          - httpd
          - php
        state: present
      when: ansible_distribution == "Red-hat"

    - name: Install repository index
      yum:
        update_cache: yes
      when: ansible_distribution == "Red-hat"
