---
- hosts: all
  become: true
  tasks:
    - name: Installing Apache & PHP support and updating cache
      apt:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: present
        update_cache: yes
