---
- hosts: all
  become: true
  tasks:
    - name: Install updates (RHEL)
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
    - name: Installing Apache & PHP support for Ubuntu servers
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Installing Apache & PHP support for Red-Hat servers
      yum:
        name:
          - httpd
          - php
        state: present
      when: ansible_distribution == "RedHat"

- hosts: db_servers
  become: true
  tasks:
    - name: Install MariaDB package "RHEL"
      dnf:
        name:
          - mariadb
          - mariadb-server
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Install MariaDB package "Ubuntu"
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: Install Samba package
      package:
        name: samba
        state: latest
