---
- hosts: all
  become: true
  pre_tasks:
    - name: Updating cache only for (Debian)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_facts['os_family'] == "Debian"

    - name: Updating cache only for (RHEL)
      tags: always
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      changed_when: false
      when: ansible_facts['os_family'] == "RedHat"

- hosts: all
  become: true
  roles:
    - base

- hosts: master_servers
  become: true
  roles:
    - master_servers

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
