---
- hosts: all
  become: true
  pre_tasks:
    - name: Install updates (RHEL)
      tags: always
      dnf:
        name: "*"
        state: latest
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
    - name: Stop Apache service
      ansible.builtin.systemd:
        name: apache2
        state: stopped
        enabled: no
      when: ansible_os_family == "Debian"

    - name: Uninstall Apache and remove configuration files
      ansible.builtin.apt:
        name: apache2
        state: absent
        purge: yes
        autoremove: yes
      when: ansible_os_family == "Debian"

    - name: Stop Apache service
      ansible.builtin.systemd:
        name: httpd
        state: stopped
        enabled: no
      when: ansible_os_family == "RedHat"

    - name: Uninstall Apache and remove configuration files
      ansible.builtin.yum:
        name: httpd
        state: absent
        remove_dependencies: yes
      when: ansible_os_family == "RedHat"

    - name: Installing nginx & PHP support for Ubuntu servers
      tags: nginx, php, Ubuntu
      apt:
        name:
          - nginx
          - php
        state: present
      when: ansible_os_family == "Ubuntu"

    - name: Installing nginx & PHP support for Red-Hat servers
      tags: nginx, redhat
      yum:
        name:
          - nginx
          - php
          - php-fpm
        state: present
      when: ansible_os_family == "RedHat"

    - name: Starting Nginx servive
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

- hosts: db_servers
  become: true
  tasks:
    - name: Install MariaDB package "RHEL"
      tags: redhat, db, mariadb
      dnf:
        name:
          - mariadb
          - mariadb-server
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install MariaDB package "Ubuntu"
      tags: ubuntu, db, mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_os_family == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
    - name: Install Samba package
      tags: samba
      package:
        name: samba
        state: latest
